const PDFDocument = require('pdfkit');

function fmtInr(n) {
  return `INR ${Number(n || 0).toLocaleString('en-IN')}`;
}

function monthLabel(month) {
  if (!month) return '';
  try {
    return new Date(`${month}-01`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  } catch {
    return month;
  }
}

function buildPayslipPdf({ employee, payroll }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const name = employee?.personalDetails?.name || 'Employee';
    const month = monthLabel(payroll.month);

    doc.fontSize(20).fillColor('#0D4F4F').text('PAYSLIP', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#666').text(month, { align: 'center' });
    doc.moveDown(1);

    doc.fontSize(10).fillColor('#000');
    doc.text(`Employee: ${name}`);
    doc.text(`Employee ID: ${employee?.employeeId || '—'}`);
    doc.text(`Department: ${employee?.department || '—'} · ${employee?.designation || '—'}`);
    doc.moveDown(1);

    const otherDed = Math.max(0, Number(payroll.deductions || 0) - Number(payroll.leaveDeduction || 0));

    doc.fontSize(12).fillColor('#0D4F4F').text('Earnings');
    doc.fontSize(10).fillColor('#000');
    doc.text(`Basic Salary: ${fmtInr(payroll.basic)}`);
    doc.text(`Allowance: ${fmtInr(payroll.allowance)}`);
    doc.text(`Bonus: ${fmtInr(payroll.bonus)}`);
    doc.moveDown(0.8);

    doc.fontSize(12).fillColor('#0D4F4F').text('Deductions');
    doc.fontSize(10).fillColor('#000');
    doc.text(`Tax (TDS): ${fmtInr(payroll.tax)}`);
    if (payroll.leaveDeduction) doc.text(`Leave deduction: ${fmtInr(payroll.leaveDeduction)}`);
    doc.text(`Other deductions: ${fmtInr(otherDed)}`);
    doc.moveDown(1);

    doc.fontSize(14).fillColor('#059669').text(`Net Pay: ${fmtInr(payroll.netPay)}`, { underline: true });
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#888').text('Generated by NeuroHR AI Payroll. For queries contact HR.', { align: 'center' });

    doc.end();
  });
}

module.exports = { buildPayslipPdf, monthLabel };
