const mongoose = require('mongoose');
const { Schema } = mongoose;

const counterSchema = new Schema({ _id: String, seq: { type: Number, default: 0 } });
const Counter = mongoose.model('Counter', counterSchema);

async function getNextSeq(name) {
  const c = await Counter.findByIdAndUpdate(name, { $inc: { seq: 1 } }, { upsert: true, new: true });
  return c.seq;
}

const userSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  name: String,
  email: { type: String, unique: true, index: true },
  passwordHash: String,
  role: { type: String, enum: ['management_admin', 'senior_manager', 'hr_recruiter', 'employee', 'candidate'], index: true },
  permissions: [String],
  department: String,
  isActive: { type: Boolean, default: true },
}, { timestamps: true });
userSchema.index({ role: 1, isActive: 1 });

const employeeSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: String, unique: true, index: true },
  userId: { type: Number, index: true },
  personalDetails: { name: String, email: String, phone: String, address: String, dob: String },
  department: { type: String, index: true },
  designation: String,
  managerId: { type: Number, index: true },
  skills: [String],
  salary: { basic: Number, allowance: Number, bonus: Number },
  employmentType: { type: String, enum: ['internship', 'full_time'], default: 'full_time', index: true },
  gender: { type: String, enum: ['male', 'female', 'other'], default: 'other' },
  jobId: Number,
  applicationId: Number,
  leaveEntitlements: Schema.Types.Mixed,
  leaveUsed: Schema.Types.Mixed,
  hiredAt: Date,
  documents: [{ name: String, path: String, type: String }],
  experience: [{ company: String, years: Number, role: String }],
  aiPerformanceScore: { type: Number, default: 0 },
  status: { type: String, default: 'active', index: true },
}, { timestamps: true });

const candidateSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  userId: { type: Number, index: true },
  name: String,
  email: { type: String, index: true },
  contactEmail: String,
  phone: String,
  jobId: { type: Number, index: true },
  resumePath: String,
  extractedData: Schema.Types.Mixed,
  skills: [String],
  experience: [Schema.Types.Mixed],
  education: [Schema.Types.Mixed],
  resumeEmbedding: [Number],
  matchScore: { type: Number, default: 0, index: true },
  rankingScore: { type: Number, default: 0 },
  featureScores: Schema.Types.Mixed,
  skillMatch: Schema.Types.Mixed,
  missingSkills: [String],
  source: { type: String, index: true },
  status: { type: String, default: 'applied', index: true },
  employeeId: { type: Number, index: true },
}, { timestamps: true });
candidateSchema.index({ jobId: 1, rankingScore: -1 });

const jobSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  title: String,
  description: String,
  skills: [String],
  niceToHaveSkills: [String],
  skillsMatrix: Schema.Types.Mixed,
  jdJson: Schema.Types.Mixed,
  techStackProfile: Schema.Types.Mixed,
  pipeline: [Schema.Types.Mixed],
  experienceLevel: String,
  difficultyLevel: String,
  interviewQuestions: [Schema.Types.Mixed],
  salaryInsights: Schema.Types.Mixed,
  createdBy: Number,
  createdByName: String,
  generatedBy: String,
  kbRepos: [String],
  employmentType: { type: String, enum: ['internship', 'full_time'], default: 'full_time', index: true },
  department: String,
  approvedBy: Number,
  approvedByName: String,
  approvedAt: Date,
  status: { type: String, default: 'open', index: true },
}, { timestamps: true });

const jobApplicationSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  jobId: { type: Number, index: true },
  candidateId: { type: Number, index: true },
  userId: Number,
  candidateName: String,
  candidateEmail: String,
  jobTitle: String,
  coverNote: String,
  phone: String,
  resumePath: String,
  resumeFileName: String,
  resumeMimeType: String,
  resumeData: Buffer,
  skills: [String],
  highlightedSkills: [String],
  jdScore: { type: Number, default: 0 },
  matchScore: { type: Number, default: 0 },
  screening: Schema.Types.Mixed,
  parsedData: Schema.Types.Mixed,
  jdFitSummary: String,
  recommendation: String,
  missingSkills: [String],
  matchedSkills: [String],
  autoShortlisted: { type: Boolean, default: false },
  autoShortlistedAt: Date,
  status: { type: String, default: 'applied', index: true },
  appliedAt: { type: Date, default: Date.now },
  aiInterviewReview: {
    decision: String,
    note: String,
    reviewedBy: Number,
    reviewedByName: String,
    reviewedAt: Date,
  },
  humanInterview: {
    interviewDate: String,
    interviewTime: String,
    durationMinutes: { type: Number, default: 60 },
    meetLink: String,
    calendarEventId: String,
    calendarHtmlLink: String,
    meetLinkSource: String,
    interviewers: [{ employeeId: Number, name: String, email: String, role: String, designation: String, department: String }],
    notes: String,
    roundNumber: { type: Number, default: 1 },
    status: String,
    scheduledBy: Number,
    scheduledByName: String,
    scheduledAt: Date,
    completedBy: Number,
    completedByName: String,
    completedAt: Date,
    panelNotes: String,
  },
  finalDecision: {
    decision: String,
    salary: String,
    startDate: String,
    message: String,
    offerResponse: String,
    offerRespondedAt: Date,
    candidateNote: String,
    offerEmailSentAt: Date,
    offerLetterHtml: String,
    offerLetterSubject: String,
    decidedBy: Number,
    decidedByName: String,
    decidedAt: Date,
  },
}, { timestamps: true });
jobApplicationSchema.index({ jobId: 1, candidateId: 1 }, { unique: true });

const notificationSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  userId: { type: Number, index: true },
  type: { type: String, default: 'info', index: true },
  title: String,
  message: String,
  link: String,
  meta: Schema.Types.Mixed,
  read: { type: Boolean, default: false, index: true },
}, { timestamps: true });

const interviewSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  userId: { type: Number, index: true },
  candidateId: { type: Number, index: true },
  applicationId: { type: Number, index: true },
  jobId: Number,
  jobTitle: String,
  jobDescription: String,
  questions: [Schema.Types.Mixed],
  answers: [Schema.Types.Mixed],
  qaLog: [Schema.Types.Mixed],
  voiceScore: { type: Number, default: 0 },
  videoScore: Schema.Types.Mixed,
  technicalScore: { type: Number, default: 0 },
  communicationScore: { type: Number, default: 0 },
  confidenceScore: { type: Number, default: 0 },
  jdAlignmentScore: { type: Number, default: 0 },
  problemSolvingScore: { type: Number, default: 0 },
  cultureFitScore: { type: Number, default: 0 },
  experienceDepthScore: { type: Number, default: 0 },
  screeningScore: { type: Number, default: 0 },
  interviewScore: { type: Number, default: 0 },
  compositeScore: { type: Number, default: 0 },
  shortlistVerdict: String,
  verdict: String,
  topStrengths: [String],
  concerns: [String],
  evaluationMethod: String,
  sentimentScore: { type: Number, default: 0 },
  fluencyScore: { type: Number, default: 0 },
  finalScore: { type: Number, default: 0 },
  recommendation: String,
  aiFeedback: String,
  perAnswerFeedback: [Schema.Types.Mixed],
  harnessEvaluation: Schema.Types.Mixed,
  harnessTranscript: [Schema.Types.Mixed],
  transcript: String,
  recordingPath: String,
  recordingDuration: Number,
  durationMinutes: { type: Number, default: 30 },
  scheduledAt: { type: Date, index: true },
  deadlineAt: { type: Date, index: true },
  scheduledBy: Number,
  scheduledByName: String,
  candidateName: String,
  candidateEmail: String,
  startedAt: Date,
  submittedAt: Date,
  analysisStatus: { type: String, default: 'pending', index: true },
  status: { type: String, default: 'pending', index: true },
  completedAt: Date,
}, { timestamps: true });

const attendanceSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: Number, index: true },
  date: { type: String, index: true },
  checkIn: String,
  checkOut: String,
  workingHours: { type: Number, default: 0 },
  faceVerification: { type: Boolean, default: false },
  verificationScore: { type: Number, default: 0 },
  status: { type: String, default: 'present' },
}, { timestamps: true });
attendanceSchema.index({ employeeId: 1, date: 1 }, { unique: true });

const leaveSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: Number, index: true },
  type: String,
  fromDate: String,
  toDate: String,
  days: { type: Number, default: 1 },
  year: Number,
  reason: String,
  status: { type: String, default: 'pending', index: true },
  approvedBy: Number,
}, { timestamps: true });

const payrollSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: Number, index: true },
  month: { type: String, index: true },
  basic: Number,
  allowance: Number,
  bonus: Number,
  deductions: Number,
  tax: Number,
  netPay: Number,
  anomalyFlag: { type: Boolean, default: false },
  leaveDeduction: { type: Number, default: 0 },
  leaveBreakdown: [Schema.Types.Mixed],
  aiPrediction: Schema.Types.Mixed,
}, { timestamps: true });
payrollSchema.index({ employeeId: 1, month: 1 }, { unique: true });

const performanceSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: Number, index: true },
  tasks: [Schema.Types.Mixed],
  goals: [Schema.Types.Mixed],
  kpis: [Schema.Types.Mixed],
  feedback: [Schema.Types.Mixed],
  projects: [Schema.Types.Mixed],
  aiScore: { type: Number, default: 0 },
  promotionChance: { type: Number, default: 0 },
  attritionRisk: { type: Number, default: 0 },
  period: String,
}, { timestamps: true });

const aiModelSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  modelName: String,
  algorithm: String,
  accuracy: Number,
  precision: Number,
  recall: Number,
  f1Score: Number,
  version: String,
  modelPath: String,
  confusionMatrix: Schema.Types.Mixed,
  status: { type: String, default: 'trained' },
}, { timestamps: true });

const chatHistorySchema = new Schema({
  id: { type: Number, unique: true, index: true },
  userId: { type: Number, index: true },
  sessionId: { type: String, index: true },
  messages: [{ role: String, content: String, timestamp: Date }],
  aiResponses: [String],
}, { timestamps: true });

const onboardingSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  candidateId: Number,
  offerLetter: String,
  joiningChecklist: [Schema.Types.Mixed],
  trainingPlan: Schema.Types.Mixed,
  day30Plan: Schema.Types.Mixed,
  day60Plan: Schema.Types.Mixed,
  day90Plan: Schema.Types.Mixed,
  documentation: [Schema.Types.Mixed],
  status: String,
}, { timestamps: true });

const reimbursementSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: { type: Number, index: true },
  employeeName: String,
  employeeEmail: String,
  category: String,
  amount: Number,
  currency: { type: String, default: 'INR' },
  description: String,
  receiptPath: String,
  status: { type: String, default: 'pending', index: true },
  reviewedBy: Number,
  reviewedAt: Date,
  hrNote: String,
}, { timestamps: true });

const documentSchema = new Schema({
  id: { type: Number, unique: true, index: true },
  employeeId: Number,
  candidateId: Number,
  documentType: String,
  filePath: String,
  extractedText: String,
  extractedFields: Schema.Types.Mixed,
  verificationScore: Number,
  ocrConfidence: Number,
}, { timestamps: true });

module.exports = {
  getNextSeq,
  User: mongoose.model('User', userSchema),
  Employee: mongoose.model('Employee', employeeSchema),
  Candidate: mongoose.model('Candidate', candidateSchema),
  Job: mongoose.model('Job', jobSchema),
  JobApplication: mongoose.model('JobApplication', jobApplicationSchema),
  Notification: mongoose.model('Notification', notificationSchema),
  Interview: mongoose.model('Interview', interviewSchema),
  Attendance: mongoose.model('Attendance', attendanceSchema),
  Leave: mongoose.model('Leave', leaveSchema),
  Payroll: mongoose.model('Payroll', payrollSchema),
  Performance: mongoose.model('Performance', performanceSchema),
  AIModel: mongoose.model('AIModel', aiModelSchema),
  ChatHistory: mongoose.model('ChatHistory', chatHistorySchema),
  Onboarding: mongoose.model('Onboarding', onboardingSchema),
  Document: mongoose.model('Document', documentSchema),
  Reimbursement: mongoose.model('Reimbursement', reimbursementSchema),
};
